version: '3'

services:
    fastapi:
      build: fastapi/
      ports: 
        - 8000:8000
      networks:
        - deploy_network
      container_name: fastapi

networks:
    deploy_network:
        driver: bridge